### ISSUE TITLE
reusing view in Layout

### ISSUE THREAD

**Issue by oozoofrog** [ioskrew/SwiftLayout#240]

**Comment by gsgod** [comment]
When i call sl.updateLayout() function, the view in Layout bring to front.  Is it a related issue?

**Comment by oozoofrog** [comment]
@gsgod oh, you right. i forgot that.

**Comment by oozoofrog** [comment]
@gmlwhdtjd root view implementing SwiftLayout can be with other sibling normal view. and can cause problem to indexing of other siblings.

**Comment by gmlwhdtjd** [comment]
@oozoofrog 
To solve the zOrder problem of views used in SwiftLayout, when calling the Layout.update() method, the addSubview() method is called for all views included in the layout.
Because of this, the zOrder of a normal view that is not included in SwiftLayout goes behind the view included in SwiftLayout.

To solve this issue, there seems to be a way to check that the hierarchy and order of views are not changed in the update() method and call addSubview() method only when a change occurs.
However, since this way requires additional resources, it will be a deduction factor in terms of performance.

**Comment by gsgod** [comment]
@oozoofrog  @gmlwhdtjd  Thanks for quick check up. : )
